package src.Main.ControlCenter;

public enum MissionStatus
{
    MISSION_START,
    TARGET_REACHED,
    TREATED_ON_SITE,
    DEPARTING_CODE1,
    DEPARTING_CODE2,
    DEPARTING_CODE3,
    DEPARTING_CODE4,
    DESTINATION_REACHED,
    MISSION_END,
    RETURNED_TO_HQ
}
